### ISSUE TITLE
TypeError: Cannot read property 'defaultView' of undefined

### ISSUE THREAD

**Issue by stevenvachon** [eventualbuddha/keysim.js#50]
```
TypeError: Cannot read property 'defaultView' of undefined
	    at Keyboard.createEventFromKeystroke (/project/node_modules/keysim/dist/keysim.js:176:31)
	    at Keyboard.dispatchEventsForKeystroke (/project/node_modules/keysim/dist/keysim.js:291:31)
	    at Keyboard.dispatchEventsForInput (/project/node_modules/keysim/dist/keysim.js:240:16)
```

Using Chrome 67.0.3396.62 (in headless mode) on macOS

**Comment by eventualbuddha** [comment]
Thanks for reporting! Can you include some of the code that triggers this? Instructions to reproduce would be very helpful as well.

**Comment by stevenvachon** [comment]
My mistake. I had sent in a jQuery instance. Thank you for the quick response!
